#!/bin/bash

# declare parameter list array
PARAMETERS=()

# read arguments
# help:
# help: Usage: %scriptname% [options...]
while [[ $# > 0 ]]; do
    case "$1" in
        # help:  -h,    --help                    Shows this help.
        # help:
        -h|--help)
            cat "$BASH_SOURCE" | grep "# help:" | grep -v 'cat parameter' | sed 's/[ ]*# help:[ ]\?//g' | sed "s~%scriptname%~$scriptname~g"
            exit 0
            ;;

        # help:  -v,    --version                 Shows the version number.
        # help:
        -v|--version)
            version=$(getCurrentTagFromGivenPath "$pathRoot")
            echo "$version"
            exit 0
            ;;

        #
        # collect all unknown parameters
        #
        *)
            PARAMETERS+=("$1")
            ;;
    esac
    shift
done

